# Generated by Django 5.2.4 on 2025-08-14 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postcategory',
            unique_together={('post', 'category')},
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_digest_sent', models.DateTimeField(blank=True, null=True, verbose_name='Последняя рассылка')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отписки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digest_subscriber', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подписчик на рассылку',
                'verbose_name_plural': 'Подписчики на рассылку',
            },
        ),
    ]
