# Generated by Django 5.2.4 on 2025-08-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0002_alter_postcategory_unique_together_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='digest_subscribers', to='NewsPortal.category'),
        ),
    ]
